### ISSUE TITLE
Frequency controllers are linear

### ISSUE THREAD

**Issue by SpacemanPaul** [attilammagyar/js80p#1]
All the frequency (Hz) based controllers go from:

* full off = 1Hz
* Half on = 12kHz
* Full on = 24 kHz

This is basically unusable for synthesis.

All manual adjustment needs to be done to these parameters on a logarithmic scale - 1 volt per octave.

All internal modulation should work like that on frequency parameters too.

**Comment by attilammagyar** [comment]
Thanks for the idea, I'll consider implementing this later.

**Comment by attilammagyar** [comment]
Logarithmic scale filter cutoff frequency support will be released in v1.4.0 in a few days.
