### ISSUE TITLE
LFO tempo sync

### ISSUE THREAD

**Issue by attilammagyar** [attilammagyar/js80p#5]
It would be nice to be able to synchronize the frequency of an LFO to the host's tempo.

(It could be just a small checkbox-like thing on the UI somewhere, which would make an LFO's frequency parameter to be interpreted as oscillations per beat instead of oscillations per second, Hz.)

**Comment by maylortaylor** [comment]
I was the one who suggested this to your on Twitter.
Love seeing how quickly you added it to the backlog!

This would be really nice to have on a per-LFO basis. So you could have LFO 1 beat synced and LFO would still be HZ synced.

Bonus points for adding ability to double/half the incoming BPM. Imagine having LFO 1 synced to the BPM and LFO 2 synced to the BPM * 2 (double-speed) and LFO 3 synced to the BPM / 2 (half-speed)

**Comment by attilammagyar** [comment]
Yes, the idea was to add a tempo sync checkbox to each LFO separately, perhaps to the currently not utilized title area of them. This checkbox would just change how the frequency is interpreted: instead of oscillations per second, it would become oscillations per beat for those LFOs which have the checkbox ticked. This wouldn't just enable e.g. double speed for one LFO, and triple speed for another, but you could also sync to triplets, or any other rythmic interval you like, because the frequency parameter would still be functional. It would also leave the possibility open to control one LFO's frequency by another LFO (which could also be tempo-synced, or not).

**Comment by attilammagyar** [comment]
LFO and Echo tempo sync will be released in v1.4.0 in a few days.
